# This file was generated by GoReleaser. DO NOT EDIT.
cask "dirtree" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "96262fa842b48a57ea45dd93b2b89881a36542d1fa96a4e030895736ddec90f4"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "53a7e1864b5741fe518e8a0ae4dbdd838f3850967dd3928dc36a40f47ffd3d6c"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d753a1243e9056e525a4be202802ea2c50e6f82322c286bc0afa473ed528fc96"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5baf79c1fbd401b2b5927dc8dd57ad02d5c0434fa92d877eaebae0c5d20d3c2b"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dirtree"
  desc "Terminal directory-tree browser: progressive-disclosure navigation, fuzzy-finder jump mode, syntax-highlighted preview"
  homepage "https://github.com/nitti/dirtree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dirtree"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dirtree"]
    end
  end

  # No zap stanza required

end
