# This file was generated by GoReleaser. DO NOT EDIT.
cask "dirtree" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "e5a0768c7fda456a737ab6d73d5f0ef37ca935b02d3415e655b46766c6b56bdd"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "29b2f272519dc5100c82f16b58baad440f95b9b9d18a9c1f2207ee0e444ce310"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "21238ebcaf9265c66ac6baa0939d3a620e76ce6d0365b9d99149e980a1700264"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "12eef75832b3471d73c874f0f2c699e6e5344d644e699216f655ae74634094df"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dirtree"
  desc "Terminal directory-tree browser: progressive-disclosure navigation, fuzzy-finder jump mode, syntax-highlighted preview"
  homepage "https://github.com/nitti/dirtree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dirtree"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dirtree"]
    end
  end

  # No zap stanza required

end
