# This file was generated by GoReleaser. DO NOT EDIT.
cask "dirtree" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "0cfcbfbf66be9dacca3b836cb78f60aad3b05b2dcf86410ffe9b9cae83af55f0"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb0e31b19a65b4fc159f43af8a3869ccadf30e0137483b32c9da4d803a2af759"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "10496fdb4a8063b7b640dc2e0b87811797da5bf63e1dee383bb7d773779e6a41"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b75f4097043c1e5ea93528f8599bfc3853270ec6f2af8abf195db0da3a1283a5"
      url "https://github.com/nitti/dirtree/releases/download/v#{version}/dirtree_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dirtree"
  desc "Terminal directory-tree browser: progressive-disclosure navigation, fuzzy-finder jump mode, syntax-highlighted preview"
  homepage "https://github.com/nitti/dirtree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dirtree"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dirtree"]
    end
  end

  # No zap stanza required

end
